import { z } from 'zod';

export const SiteFormSchema = z.object({
  id: z.number(),
  siteid: z.string().min(8).nonempty({message: 'Site ID is required'}),
  sitename: z.string().min(2).nonempty({message: 'Site Name is required'}),
  cluster: z.string().min(2).nonempty({message: 'Cluster is required'}),
  contracttype: z.string().min(1),
  siteconfig: z.string().min(1),
  region: z.string().min(1),
  state: z.string().min(1),
  lat: z.string().min(1),
  lon: z.string().min(1),
})

export const PhysicalSiteFormSchema = z.object({
  cellidentity: z.number(),
  sitebasicinfo: z.number().min(1),
  antennatype: z.string().min(1),
  sitestatus: z.string(),
  sectorid: z.number().min(0),
  enbid: z.string().min(1),
  portnumber: z.number().min(0),
  siteconfig: z.string().min(1),
  sectorconfig: z.number().min(1),
  channelcard: z.string().min(1),
  antennaheight: z.number().min(0),
  azimuth: z.number().min(0).max(360),
  mtilt: z.number().min(0).max(30),
  etilt: z.number().min(0).max(12),
  earfcndl: z.number().min(1),
  earfcnul: z.number().min(1),
  pci: z.number().min(0).max(503),
  rsi: z.number().min(0),
  tac: z.number().min(1),
  pss: z.number().min(0).max(2),
  sss: z.number().min(0),
  txattn: z.number().min(0).max(300),
  update_status: z.string().nullable(),
})

export const DoFormSchema = z.object({
  id: z.number(),
  sitebasicinfo: z.string().min(1).nullable(),
  doissuedate: z.string().nullable(),
  codsubmitdate: z.string().nullable(),
  codapprovedate: z.string().nullable(),
})

export const InstallFormSchema = z.object({
  id: z.number(),
  sitebasicinfo: z.string().min(1),
  installdelay: z.string().nullable(),
  integratedelay:  z.string().nullable(),
  onairdelay:  z.string().nullable(),
  coidelay:  z.string().nullable(),
  coicdelay:  z.string().nullable(),
  subcon:  z.string().nullable(),
  install_start:  z.string().nullable(),
  install_complete:  z.string().nullable(),
  installdelay_detail:  z.string().nullable(),
  integration_date:  z.string().nullable(),
  integration_turnon:  z.string().nullable(),
  integratedelay_detail:  z.string().nullable(),
  onair_date:  z.string().nullable(),
  onairdelay_detail:  z.string().nullable(),
  coi_submit_date:  z.string().nullable(),
  coi_approval_date:  z.string().nullable(),
  coidelay_detail:  z.string().nullable(),
  coic_submit_date:  z.string().nullable(),
  coic_approval_status:  z.string().nullable(),
  coicdelay_detail:  z.string().nullable(),
  pnoc_ho_trigger_date:  z.string().nullable(),
  pnoc_ho_complete_date:  z.string().nullable(),
  modify_date:  z.string().nullable(),
})